"""
Articulatory and Acoustic Parameter Tables for Phonemes and Creature Sounds.
Maps symbols to formants, noise bands, burst profiles, and Extended IPA metadata.
"""

from typing import Dict, Any, List, Optional


# Comprehensive Vowel Formant Presets (F1, F2, F3, F4, F5 in Hz) and bandwidths (B1, B2, B3, B4, B5)
VOWEL_TABLE: Dict[str, Dict[str, Any]] = {
    "i": {
        "ipa": "i",
        "name": "Close front unrounded",
        "formants": [280, 2250, 2800, 3500, 4200],
        "bandwidths": [60, 90, 150, 200, 250],
        "nasal": False,
    },
    "y": {
        "ipa": "y",
        "name": "Close front rounded",
        "formants": [280, 1900, 2400, 3300, 4100],
        "bandwidths": [60, 100, 160, 200, 250],
        "nasal": False,
    },
    "e": {
        "ipa": "e",
        "name": "Close-mid front unrounded",
        "formants": [400, 2000, 2600, 3400, 4200],
        "bandwidths": [70, 100, 150, 200, 250],
        "nasal": False,
    },
    "eps": {
        "ipa": "ɛ",
        "name": "Open-mid front unrounded",
        "formants": [550, 1750, 2500, 3500, 4200],
        "bandwidths": [80, 110, 160, 220, 250],
        "nasal": False,
    },
    "ae": {
        "ipa": "æ",
        "name": "Near-open front unrounded",
        "formants": [700, 1600, 2450, 3400, 4200],
        "bandwidths": [90, 120, 170, 220, 260],
        "nasal": False,
    },
    "a": {
        "ipa": "a",
        "name": "Open central unrounded",
        "formants": [800, 1300, 2400, 3500, 4200],
        "bandwidths": [90, 120, 160, 220, 260],
        "nasal": False,
    },
    "schwa": {
        "ipa": "ə",
        "name": "Mid-central neutral",
        "formants": [500, 1500, 2500, 3500, 4200],
        "bandwidths": [80, 100, 150, 200, 250],
        "nasal": False,
    },
    "ax": {
        "ipa": "ə",
        "name": "Mid-central neutral",
        "formants": [500, 1500, 2500, 3500, 4200],
        "bandwidths": [80, 100, 150, 200, 250],
        "nasal": False,
    },
    "turn_m": {
        "ipa": "ɯ",
        "name": "Close back unrounded",
        "formants": [300, 1350, 2350, 3400, 4200],
        "bandwidths": [70, 110, 160, 200, 250],
        "nasal": False,
    },
    "u": {
        "ipa": "u",
        "name": "Close back rounded",
        "formants": [300, 850, 2300, 3300, 4100],
        "bandwidths": [60, 80, 140, 200, 250],
        "nasal": False,
    },
    "o": {
        "ipa": "o",
        "name": "Close-mid back rounded",
        "formants": [450, 950, 2400, 3400, 4200],
        "bandwidths": [70, 90, 150, 200, 250],
        "nasal": False,
    },
    "open_o": {
        "ipa": "ɔ",
        "name": "Open-mid back rounded",
        "formants": [580, 900, 2400, 3400, 4200],
        "bandwidths": [80, 100, 150, 200, 250],
        "nasal": False,
    },
    "nasal_a": {
        "ipa": "ã",
        "name": "Nasalized open central",
        "formants": [750, 1300, 2200, 3300, 4100],
        "bandwidths": [120, 150, 200, 250, 300],
        "nasal": True,
    },
    "nasal_o": {
        "ipa": "õ",
        "name": "Nasalized close-mid back",
        "formants": [450, 900, 2100, 3200, 4000],
        "bandwidths": [110, 140, 190, 240, 300],
        "nasal": True,
    },
}


# Consonant and Non-Pulmonic Acoustic Profiles
CONSONANT_TABLE: Dict[str, Dict[str, Any]] = {
    # --- Plosives / Stops ---
    "p": {
        "ipa": "p",
        "manner": "plosive",
        "place": "bilabial",
        "voiced": False,
        "burst_freq": 1000,
        "burst_bandwidth": 800,
        "burst_duration_ms": 15,
        "aspiration_duration_ms": 25,
        "formants": [300, 800, 2200, 3400, 4200],
    },
    "b": {
        "ipa": "b",
        "manner": "plosive",
        "place": "bilabial",
        "voiced": True,
        "burst_freq": 1000,
        "burst_bandwidth": 800,
        "burst_duration_ms": 12,
        "voice_bar": True,
        "formants": [250, 900, 2200, 3400, 4200],
    },
    "t": {
        "ipa": "t",
        "manner": "plosive",
        "place": "alveolar",
        "voiced": False,
        "burst_freq": 3800,
        "burst_bandwidth": 1200,
        "burst_duration_ms": 15,
        "aspiration_duration_ms": 30,
        "formants": [300, 1600, 2600, 3500, 4200],
    },
    "d": {
        "ipa": "d",
        "manner": "plosive",
        "place": "alveolar",
        "voiced": True,
        "burst_freq": 3600,
        "burst_bandwidth": 1200,
        "burst_duration_ms": 12,
        "voice_bar": True,
        "formants": [250, 1650, 2550, 3500, 4200],
    },
    "k": {
        "ipa": "k",
        "manner": "plosive",
        "place": "velar",
        "voiced": False,
        "burst_freq": 2200,
        "burst_bandwidth": 700,
        "burst_duration_ms": 20,
        "aspiration_duration_ms": 35,
        "formants": [300, 2000, 2400, 3500, 4200],
    },
    "g": {
        "ipa": "g",
        "manner": "plosive",
        "place": "velar",
        "voiced": True,
        "burst_freq": 2100,
        "burst_bandwidth": 700,
        "burst_duration_ms": 15,
        "voice_bar": True,
        "formants": [250, 1950, 2350, 3500, 4200],
    },
    "q": {
        "ipa": "q",
        "manner": "plosive",
        "place": "uvular",
        "voiced": False,
        "burst_freq": 1400,
        "burst_bandwidth": 600,
        "burst_duration_ms": 22,
        "aspiration_duration_ms": 35,
        "formants": [450, 1200, 2200, 3400, 4200],
    },
    "glottal_stop": {
        "ipa": "ʔ",
        "manner": "plosive",
        "place": "glottal",
        "voiced": False,
        "burst_freq": 0,
        "burst_duration_ms": 0,
        "glottal_closure": True,
    },
    # --- Fricatives ---
    "s": {
        "ipa": "s",
        "manner": "fricative",
        "place": "alveolar",
        "voiced": False,
        "noise_center": 5200,
        "noise_bandwidth": 2500,
        "formants": [300, 1600, 2600, 3600, 4400],
    },
    "z": {
        "ipa": "z",
        "manner": "fricative",
        "place": "alveolar",
        "voiced": True,
        "noise_center": 5000,
        "noise_bandwidth": 2400,
        "formants": [250, 1600, 2600, 3600, 4400],
    },
    "sh": {
        "ipa": "ʃ",
        "manner": "fricative",
        "place": "postalveolar",
        "voiced": False,
        "noise_center": 3200,
        "noise_bandwidth": 2000,
        "formants": [350, 1800, 2700, 3600, 4300],
    },
    "zh": {
        "ipa": "ʒ",
        "manner": "fricative",
        "place": "postalveolar",
        "voiced": True,
        "noise_center": 3000,
        "noise_bandwidth": 1900,
        "formants": [300, 1750, 2650, 3600, 4300],
    },
    "f": {
        "ipa": "f",
        "manner": "fricative",
        "place": "labiodental",
        "voiced": False,
        "noise_center": 4000,
        "noise_bandwidth": 3500,
        "formants": [300, 1200, 2400, 3400, 4200],
    },
    "v": {
        "ipa": "v",
        "manner": "fricative",
        "place": "labiodental",
        "voiced": True,
        "noise_center": 3800,
        "noise_bandwidth": 3200,
        "formants": [250, 1200, 2400, 3400, 4200],
    },
    "x_velar": {
        "ipa": "x",
        "manner": "fricative",
        "place": "velar",
        "voiced": False,
        "noise_center": 1800,
        "noise_bandwidth": 1200,
        "formants": [400, 1600, 2300, 3400, 4200],
    },
    "gamma": {
        "ipa": "ɣ",
        "manner": "fricative",
        "place": "velar",
        "voiced": True,
        "noise_center": 1700,
        "noise_bandwidth": 1100,
        "formants": [350, 1550, 2300, 3400, 4200],
    },
    "h": {
        "ipa": "h",
        "manner": "fricative",
        "place": "glottal",
        "voiced": False,
        "noise_center": 2200,
        "noise_bandwidth": 3000,
        "formants": [500, 1500, 2500, 3500, 4200],
    },
    # --- Nasals & Liquids ---
    "m": {
        "ipa": "m",
        "manner": "nasal",
        "place": "bilabial",
        "voiced": True,
        "formants": [250, 1100, 2200, 3300, 4100],
        "bandwidths": [100, 180, 250, 250, 300],
    },
    "n": {
        "ipa": "n",
        "manner": "nasal",
        "place": "alveolar",
        "voiced": True,
        "formants": [250, 1500, 2400, 3400, 4200],
        "bandwidths": [100, 180, 250, 250, 300],
    },
    "ng": {
        "ipa": "ŋ",
        "manner": "nasal",
        "place": "velar",
        "voiced": True,
        "formants": [250, 2000, 2500, 3500, 4200],
        "bandwidths": [100, 200, 250, 250, 300],
    },
    "l": {
        "ipa": "l",
        "manner": "approximant",
        "place": "alveolar",
        "voiced": True,
        "formants": [350, 1200, 2700, 3400, 4200],
        "bandwidths": [70, 100, 160, 200, 250],
    },
    "r_tap": {
        "ipa": "ɾ",
        "manner": "tap",
        "place": "alveolar",
        "voiced": True,
        "formants": [350, 1400, 2400, 3400, 4200],
        "bandwidths": [80, 110, 160, 200, 250],
    },
    "r_trill": {
        "ipa": "r",
        "manner": "trill",
        "place": "alveolar",
        "voiced": True,
        "trill_rate_hz": 26,
        "formants": [400, 1500, 2300, 3400, 4200],
        "bandwidths": [80, 120, 160, 200, 250],
    },
    # --- Clicks, Ejectives, Implosives ---
    "click_dental": {
        "ipa": "ǀ",
        "manner": "click",
        "place": "dental",
        "voiced": False,
        "click_peak_hz": 4800,
        "click_duration_ms": 8,
    },
    "click_alveolar": {
        "ipa": "ǃ",
        "manner": "click",
        "place": "alveolar",
        "voiced": False,
        "click_peak_hz": 1600,
        "click_duration_ms": 14,
    },
    "click_lateral": {
        "ipa": "ǁ",
        "manner": "click",
        "place": "lateral",
        "voiced": False,
        "click_peak_hz": 2800,
        "click_duration_ms": 12,
    },
    "click_bilabial": {
        "ipa": "ʘ",
        "manner": "click",
        "place": "bilabial",
        "voiced": False,
        "click_peak_hz": 950,
        "click_duration_ms": 15,
    },
    "ejective_k": {
        "ipa": "kʼ",
        "manner": "ejective",
        "place": "velar",
        "voiced": False,
        "burst_freq": 2300,
        "burst_duration_ms": 25,
        "glottal_lag_ms": 40,
    },
    "ejective_t": {
        "ipa": "tʼ",
        "manner": "ejective",
        "place": "alveolar",
        "voiced": False,
        "burst_freq": 3900,
        "burst_duration_ms": 20,
        "glottal_lag_ms": 35,
    },
    "implosive_b": {
        "ipa": "ɓ",
        "manner": "implosive",
        "place": "bilabial",
        "voiced": True,
        "prevoice_pitch_drop": True,
        "formants": [220, 850, 2100, 3300, 4100],
    },
    "implosive_d": {
        "ipa": "ɗ",
        "manner": "implosive",
        "place": "alveolar",
        "voiced": True,
        "prevoice_pitch_drop": True,
        "formants": [220, 1600, 2450, 3400, 4200],
    },
}


# Creature & Animal Bioacoustic Profiles
CREATURE_TABLE: Dict[str, Dict[str, Any]] = {
    "feline_growl": {
        "ipa": "ʭ_growl",
        "name": "Feline Ventricular Guttural Growl",
        "default_subharmonic_depth": 0.75,
        "throat_resonance_hz": [280, 850, 1950, 3100],
        "roughness": 0.8,
        "default_duration_ms": 250,
    },
    "feline_purr": {
        "ipa": "ʬ̃_purr",
        "name": "Feline Rhythmic Neural Purr",
        "default_rate_hz": 24.5,
        "default_depth": 0.85,
        "throat_resonance_hz": [320, 1100, 2100, 3200],
        "default_duration_ms": 350,
    },
    "feline_hiss": {
        "ipa": "ʩ_hiss",
        "name": "Feline Defensive Hiss",
        "noise_center": 4200,
        "noise_bandwidth": 3000,
        "intensity": 0.9,
        "default_duration_ms": 180,
    },
    "feline_chitter": {
        "ipa": "ǂ_chitter",
        "name": "Feline Excitement Jaw-Chitter",
        "chatter_rate_hz": 14.0,
        "chirp_f0": 1800,
        "default_duration_ms": 200,
    },
    "canine_snarl": {
        "ipa": "r_snarl",
        "name": "Canine Aggressive Snarl",
        "flutter_hz": 48.0,
        "lip_curl_brighten": 1.25,
        "roughness": 0.85,
        "default_duration_ms": 250,
    },
    "canine_bark": {
        "ipa": "ʔ_bark",
        "name": "Canine Chest-Impact Warning Bark",
        "chest_resonance_hz": 180,
        "pitch_decay_speed": 18.0,
        "default_duration_ms": 120,
    },
    "canine_whine": {
        "ipa": "i_whine",
        "name": "Canine High-Register Whine",
        "base_f0": 1200,
        "glide_slope": 1.4,
        "harmonics_count": 6,
        "default_duration_ms": 300,
    },
    "canine_howl": {
        "ipa": "o_howl",
        "name": "Canine Sustained Resonant Howl",
        "base_f0": 380,
        "vibrato_rate": 5.2,
        "vibrato_depth_semitones": 0.8,
        "default_duration_ms": 600,
    },
}


def get_all_symbols_metadata() -> List[Dict[str, Any]]:
    """Returns a list of all symbol definitions for frontend palette."""
    symbols = []
    
    for k, v in VOWEL_TABLE.items():
        symbols.append({
            "symbol": k,
            "ipa": v["ipa"],
            "name": v["name"],
            "category": "vowel",
            "type": "vowel",
            "formants": v["formants"],
        })
        
    for k, v in CONSONANT_TABLE.items():
        symbols.append({
            "symbol": k,
            "ipa": v["ipa"],
            "name": f"{v.get('place', '')} {v.get('manner', '')} ({'voiced' if v.get('voiced') else 'voiceless'})",
            "category": "consonant",
            "type": "consonant",
            "manner": v.get("manner"),
            "place": v.get("place"),
        })
        
    for k, v in CREATURE_TABLE.items():
        symbols.append({
            "symbol": k,
            "ipa": v["ipa"],
            "name": v["name"],
            "category": "creature",
            "type": "creature",
        })
        
    return symbols
